import io
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Table, TableStyle, Spacer, HRFlowable
from reportlab.lib.enums import TA_CENTER, TA_LEFT


NH_BLUE = colors.HexColor("#003882")
NH_GREEN = colors.HexColor("#00703C")
LIGHT_GRAY = colors.HexColor("#F5F5F5")


def generate_consultation_pdf(
    closure: dict,
    routes: list[dict],
    stakeholders: list[dict],
    ttro_ref: str = "TTRO/DRAFT",
) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=20 * mm,
        leftMargin=20 * mm,
        topMargin=20 * mm,
        bottomMargin=20 * mm,
        title=f"TTRO Consultation Pack — {ttro_ref}",
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("Title", parent=styles["Heading1"], textColor=NH_BLUE, fontSize=18, spaceAfter=6)
    h2_style = ParagraphStyle("H2", parent=styles["Heading2"], textColor=NH_BLUE, fontSize=13, spaceAfter=4)
    body_style = styles["BodyText"]
    label_style = ParagraphStyle("Label", parent=body_style, textColor=colors.gray, fontSize=9)

    story = []

    # Cover
    story.append(Paragraph("National Highways — M25 DBFO", label_style))
    story.append(Paragraph("TTRO Consultation Pack", title_style))
    story.append(Paragraph(f"Reference: {ttro_ref}", body_style))
    story.append(Paragraph(f"Generated: {datetime.utcnow().strftime('%d %B %Y %H:%M')} UTC", label_style))
    story.append(HRFlowable(width="100%", thickness=2, color=NH_BLUE))
    story.append(Spacer(1, 8 * mm))

    # Closure details
    story.append(Paragraph("1. Closure Details", h2_style))
    closure_data = [
        ["Field", "Value"],
        ["Closure Type", closure.get("closure_type", "—").replace("_", " ").title()],
        ["Direction", closure.get("direction", "N/A")],
        ["Start Junction", closure.get("start_junction") or closure.get("start_chainage") or "—"],
        ["End Junction", closure.get("end_junction") or closure.get("end_chainage") or "—"],
        ["Date From", _fmt_dt(closure.get("date_from"))],
        ["Date To", _fmt_dt(closure.get("date_to"))],
        ["Reason", closure.get("reason") or "—"],
    ]
    story.append(_table(closure_data))
    story.append(Spacer(1, 8 * mm))

    # Diversion routes
    story.append(Paragraph("2. Proposed Diversion Routes", h2_style))
    route_data = [["Rank", "Distance", "Travel Time", "Score", "HGV Suitable"]]
    for r in routes:
        breakdown = r.get("score_breakdown") or {}
        hgv_pct = breakdown.get("hgv_suitability", 100)
        route_data.append([
            _rank_label(r.get("route_rank", 1)),
            f"{r.get('distance_m', 0) / 1000:.1f} km",
            f"{r.get('travel_time_min', 0):.0f} min",
            f"{r.get('score', 0)}/100",
            f"{hgv_pct:.0f}%",
        ])
    story.append(_table(route_data, header_color=NH_BLUE))
    story.append(Spacer(1, 8 * mm))

    # Assessment scores
    story.append(Paragraph("3. Route Assessment", h2_style))
    score_headers = ["Dimension", "Weight"] + [_rank_label(r.get("route_rank", i + 1)) for i, r in enumerate(routes)]
    score_rows = [score_headers]
    dimensions = [
        ("Distance Efficiency", "20%", "distance_efficiency"),
        ("Travel Time Impact", "25%", "travel_time_impact"),
        ("HGV Suitability", "20%", "hgv_suitability"),
        ("Emergency Access", "15%", "emergency_access"),
        ("Local Authority Impact", "10%", "local_authority_impact"),
        ("Network Resilience", "10%", "network_resilience"),
    ]
    for label, weight, key in dimensions:
        row = [label, weight]
        for r in routes:
            bd = r.get("score_breakdown") or {}
            row.append(f"{bd.get(key, '—')}")
        score_rows.append(row)
    story.append(_table(score_rows, header_color=NH_GREEN))
    story.append(Spacer(1, 8 * mm))

    # Stakeholders
    story.append(Paragraph("4. Affected Stakeholders", h2_style))
    if stakeholders:
        st_data = [["Organisation", "Category", "Contact"]]
        for s in stakeholders:
            st_data.append([
                s.get("name", "—"),
                s.get("category", "—").replace("_", " ").title(),
                s.get("contact_email") or "—",
            ])
        story.append(_table(st_data, header_color=NH_BLUE))
    else:
        story.append(Paragraph("No stakeholder data available. Run stakeholder identification first.", body_style))

    story.append(Spacer(1, 12 * mm))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.lightgrey))
    story.append(Paragraph(
        "This document is auto-generated by the M25 TTRO Diversion Planner. "
        "It must be reviewed and approved by a qualified Traffic Management Designer before submission.",
        label_style,
    ))

    doc.build(story)
    return buffer.getvalue()


def _fmt_dt(value) -> str:
    if not value:
        return "—"
    if isinstance(value, str):
        return value
    return value.strftime("%d %b %Y %H:%M")


def _rank_label(rank: int) -> str:
    return {1: "Primary", 2: "Alt 1", 3: "Alt 2"}.get(rank, f"Route {rank}")


def _table(data: list, header_color=None) -> Table:
    col_count = len(data[0]) if data else 1
    t = Table(data, repeatRows=1)
    style = [
        ("BACKGROUND", (0, 0), (-1, 0), header_color or NH_BLUE),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_GRAY]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]
    t.setStyle(TableStyle(style))
    return t
