services:
  - type: web
    name: landxml-volume-api
    env: python
    region: oregon
    plan: free
    pythonVersion: "3.11.4"
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.4"
