# Generated by Django 5.2.15 on 2026-07-01 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(blank=True, help_text='e.g. Ilam, Nepal or Patan, Kathmandu', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='pack_info',
            field=models.CharField(blank=True, help_text='e.g. 1 piece or Set of 2', max_length=100, verbose_name='pack size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_info',
            field=models.CharField(blank=True, help_text='e.g. 250g or 30cm × 180cm', max_length=100, verbose_name='size / weight'),
        ),
        migrations.AddField(
            model_name='product',
            name='use_occasions',
            field=models.CharField(blank=True, help_text='e.g. Weddings, Festivals, Gifting', max_length=300),
        ),
    ]
